/* tslint:disable */
/* eslint-disable */
/**
 * Zero consult invoicing - OpenAPI 3.2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * InvoicingMonthApi - axios parameter creator
 */
export const InvoicingMonthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Close the current invoicingMonth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        closeCurrentPayslipMonth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/invoicingMonth/payslip/close`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the current payslipMonth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentPayslipMonth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/invoicingMonth/payslip`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'text/plain';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InvoicingMonthApi - functional programming interface
 */
export const InvoicingMonthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InvoicingMonthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Close the current invoicingMonth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async closeCurrentPayslipMonth(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.closeCurrentPayslipMonth(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoicingMonthApi.closeCurrentPayslipMonth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get the current payslipMonth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentPayslipMonth(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentPayslipMonth(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InvoicingMonthApi.getCurrentPayslipMonth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InvoicingMonthApi - factory interface
 */
export const InvoicingMonthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InvoicingMonthApiFp(configuration)
    return {
        /**
         * 
         * @summary Close the current invoicingMonth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        closeCurrentPayslipMonth(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.closeCurrentPayslipMonth(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the current payslipMonth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentPayslipMonth(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.getCurrentPayslipMonth(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InvoicingMonthApi - object-oriented interface
 */
export class InvoicingMonthApi extends BaseAPI {
    /**
     * 
     * @summary Close the current invoicingMonth
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public closeCurrentPayslipMonth(options?: RawAxiosRequestConfig) {
        return InvoicingMonthApiFp(this.configuration).closeCurrentPayslipMonth(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get the current payslipMonth
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCurrentPayslipMonth(options?: RawAxiosRequestConfig) {
        return InvoicingMonthApiFp(this.configuration).getCurrentPayslipMonth(options).then((request) => request(this.axios, this.basePath));
    }
}

