/* tslint:disable */
/* eslint-disable */
/**
 * Zero consult invoicing - OpenAPI 3.2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Payslip } from '../model';
/**
 * PayslipApi - axios parameter creator
 */
export const PayslipApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete a payslip
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePayslip: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePayslip', 'id', id)
            const localVarPath = `/payslips/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Add a new payslip entry
         * @param {Payslip} payslip 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generatePayslip: async (payslip: Payslip, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'payslip' is not null or undefined
            assertParamExists('generatePayslip', 'payslip', payslip)
            const localVarPath = `/payslips`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,text/plain';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(payslip, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a payslip
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPayslip: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPayslip', 'id', id)
            const localVarPath = `/payslips/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,text/plain';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the payslip file
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPayslipFile: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPayslipFile', 'id', id)
            const localVarPath = `/payslips/{id}/file`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/pdf,text/plain';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the current payslip month
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPayslipMonth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/payslips/month`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'text/plain';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the list of payslips for a given period
         * @param {string} from 
         * @param {string} until 
         * @param {string} [employeeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        payslipsList: async (from: string, until: string, employeeId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'from' is not null or undefined
            assertParamExists('payslipsList', 'from', from)
            // verify required parameter 'until' is not null or undefined
            assertParamExists('payslipsList', 'until', until)
            const localVarPath = `/payslips`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString().substring(0,10) :
                    from;
            }

            if (until !== undefined) {
                localVarQueryParameter['until'] = (until as any instanceof Date) ?
                    (until as any).toISOString().substring(0,10) :
                    until;
            }

            if (employeeId !== undefined) {
                localVarQueryParameter['employeeId'] = employeeId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PayslipApi - functional programming interface
 */
export const PayslipApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PayslipApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Delete a payslip
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePayslip(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePayslip(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PayslipApi.deletePayslip']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Add a new payslip entry
         * @param {Payslip} payslip 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generatePayslip(payslip: Payslip, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Payslip>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generatePayslip(payslip, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PayslipApi.generatePayslip']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a payslip
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPayslip(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Payslip>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPayslip(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PayslipApi.getPayslip']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get the payslip file
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPayslipFile(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPayslipFile(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PayslipApi.getPayslipFile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get the current payslip month
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPayslipMonth(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPayslipMonth(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PayslipApi.getPayslipMonth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get the list of payslips for a given period
         * @param {string} from 
         * @param {string} until 
         * @param {string} [employeeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async payslipsList(from: string, until: string, employeeId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Payslip>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.payslipsList(from, until, employeeId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PayslipApi.payslipsList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PayslipApi - factory interface
 */
export const PayslipApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PayslipApiFp(configuration)
    return {
        /**
         * 
         * @summary Delete a payslip
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePayslip(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deletePayslip(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Add a new payslip entry
         * @param {Payslip} payslip 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generatePayslip(payslip: Payslip, options?: RawAxiosRequestConfig): AxiosPromise<Payslip> {
            return localVarFp.generatePayslip(payslip, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a payslip
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPayslip(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Payslip> {
            return localVarFp.getPayslip(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the payslip file
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPayslipFile(id: string, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.getPayslipFile(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the current payslip month
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPayslipMonth(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.getPayslipMonth(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the list of payslips for a given period
         * @param {string} from 
         * @param {string} until 
         * @param {string} [employeeId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        payslipsList(from: string, until: string, employeeId?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<Payslip>> {
            return localVarFp.payslipsList(from, until, employeeId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PayslipApi - object-oriented interface
 */
export class PayslipApi extends BaseAPI {
    /**
     * 
     * @summary Delete a payslip
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deletePayslip(id: string, options?: RawAxiosRequestConfig) {
        return PayslipApiFp(this.configuration).deletePayslip(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Add a new payslip entry
     * @param {Payslip} payslip 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public generatePayslip(payslip: Payslip, options?: RawAxiosRequestConfig) {
        return PayslipApiFp(this.configuration).generatePayslip(payslip, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a payslip
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPayslip(id: string, options?: RawAxiosRequestConfig) {
        return PayslipApiFp(this.configuration).getPayslip(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get the payslip file
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPayslipFile(id: string, options?: RawAxiosRequestConfig) {
        return PayslipApiFp(this.configuration).getPayslipFile(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get the current payslip month
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getPayslipMonth(options?: RawAxiosRequestConfig) {
        return PayslipApiFp(this.configuration).getPayslipMonth(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get the list of payslips for a given period
     * @param {string} from 
     * @param {string} until 
     * @param {string} [employeeId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public payslipsList(from: string, until: string, employeeId?: string, options?: RawAxiosRequestConfig) {
        return PayslipApiFp(this.configuration).payslipsList(from, until, employeeId, options).then((request) => request(this.axios, this.basePath));
    }
}

